site_name: Python CadQuery para arquitetos
use_directory_urls: false

copyright: Copyright &copy; 2016 - 2021 Fernando Ferraz Ribeiro

theme:
  features:

    #- navigation.sections
    - toc.integrate
    #- navigation.tabs
  name: material   
  language: en-custom
  custom_dir: docs\overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      #primary: orange
      #accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  

site_url: "https://255ribeiro.github.io/cadquery_test/"
repo_url: "https://github.com/255ribeiro/cadquery_test/"
repo_name: "255ribeiro/cadquery_test" 

nav:
  - Home: index.md
  - Google Colab: 
    - intro: ./tuto_colab/cadquery_basic_gc.ipynb
    - primitivas: ./tuto_colab/cadquery_primitives_gc.ipynb
  - Vscode:
    - intro: ./tuto_vscode/cadquery_basic_vscode.ipynb
    - primitivas: ./tuto_vscode/cadquery_primitives_vscode.ipynb

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - toc:
      toc_depth: 1


plugins:
  - mkdocs-jupyter:
      #execute: True
      include_source: True


# extra:
#   social:
#       - icon: fontawesome/brands/github
#         link: https://github.com/255ribeiro
#       - icon: fontawesome/brands/youtube
#         link: https://www.youtube.com/channel/UCCkMaRdD7PBWhs4JgH5s6_w
#       - icon: fontawesome/brands/linkedin
#         link: https://www.linkedin.com/in/fernando-ferraz-ribeiro-b49a7bb0/
#       - icon: fontawesome/solid/envelope-square
#         link: mailto:ffribeiro@gmail.com
